### ISSUE TITLE
Functionality for a todo item to EASILY send itself back to unscheduled without having to use edit form

### ISSUE THREAD

**Issue by jpe442** [jpe442/dodateweb#23]
- [ ] rightClick type event tied to a dropdown with this as one of the options?
- [ ] simple Button in edit form
- [ ] <some other idea here>
